name: Deploy Job

on:
  pull_request:
    types: [closed]

jobs:

  test-feature:
    
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: install databricks-cli
      run: pip install databricks-cli
    
    - name: sync repos
      run: databricks repos update --path /Repos/victor.rodrigues@databricks.com/fraud-prod --branch prod
      env:
        DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}
        DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
      
    - name: deploy job
      run: cd jobs; python deploy_job.py
