name: Deploy Job

on:
  pull_request:
    types: [closed]

jobs:

  test-feature:
    
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: install databricks-cli
      run: pip install databricks-cli
      
    - name: deploy job
      run: cd jobs; python deploy_job.py
