name: Python Package using Conda

on:
  pull_request:
    types: [opened, reopened]

jobs:

  test-feature:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: run tests
      run: python tests/test.py
